// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbjCvQBXrvmOxKP3u_R-aKu5729qMJik',
    appId: '1:190010023895:android:06c721b7bfd21e66e23592',
    messagingSenderId: '190010023895',
    projectId: 'shop-lifter-5bba5',
    databaseURL: 'https://shop-lifter-5bba5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shop-lifter-5bba5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-c3jeW8fqkq-fhxH1zO7G0R5QgKaR0cw',
    appId: '1:190010023895:ios:4af8c499180a4e00e23592',
    messagingSenderId: '190010023895',
    projectId: 'shop-lifter-5bba5',
    databaseURL: 'https://shop-lifter-5bba5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shop-lifter-5bba5.appspot.com',
    iosBundleId: 'com.example.shopLifter',
  );
}
